#Ejercicio 5
print(" Piensa un número")
print(" Sumale 5")
print(" Multiplique 3")
print(" Restar 15")
res=int(input("Digita el número que te dió \n"))
num=res/3
print(f"El número que pensaste.....\n es .....\n {int(num)} ")
rta=input("¿Es correcto? escribe si de lo contrario no \n")
if rta=="si" :
    print("Soy todo un adivino")
elif rta=="Si":
    print("Soy todo un adivino")
elif rta=="SI":
    print("Soy todo un adivino")
elif rta=="sI":
    print("Soy todo un adivino")
else:
    print("Rectifica las cuentas te darás cuenta que no me equivoco")